### ISSUE TITLE
Zoek naar deze afbeelding bij Google werkt niet

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#59]
Als ik op de link "Zoek naar deze afbeelding bij Google" klik, krijg ik het zoekscherm van Google met de volgende foutmelding: "De URL verwijst niet naar een afbeelding of de afbeelding is niet openbaar toegankelijk."
Voorbeeld ticket: http://www.wikiportret.nl/images/single.php?id=11
Selecteer ik de rechtstreekse URL van de afbeelding (http://www.wikiportret.nl/uploads/images/mae-1435849871.jpg) en plak ik die in het URL venster van Google afbeeldingen krijg ik wel zoekresultaten.

**Comment by JurgenNL** [comment]
De link zou moeten verwijzen naar https://www.google.com/searchbyimage?image_url=http://www.wikiportret.nl/uploads/images/mae-1435849871.jpg en als ik die link in m'n browser invul, werkt het zoeken ook gewoon dus ik vermoed dat er een fout in de link staat. Naar welke link verwijst de pagina?

**Comment by mbch331** [comment]
https://www.google.com/searchbyimage?image_url=$imgurl oftewel de variabele wordt niet geresolved. (Misschien per ongeluk tussen '' ipv ""?)

**Comment by mbch331** [comment]
Je moet wel een echo toevoegen, de variabele wordt nog steeds niet geresolved.

**Comment by JurgenNL** [comment]
<?= staat gelijk aan <?php echo. :)

**Comment by mbch331** [comment]
Wanneer gaat deze fix live?

**Comment by hay** [comment]
Er zijn wat kleine probleempjes met het live zetten van de fix, hoop er vanavond aan toe te komen.

**Comment by hay** [comment]
Inmiddels al online.
