### ISSUE TITLE
Fout in antwoord

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#62]
In het antwoord "Confirmation!" staat in de eerste zin een fout. Er staat <i>upgeload</i>, maar dit moet <i>geüpload</i> zijn.

**Comment by JurgenNL** [comment]
Dat kan op de website worden aangepast door iemand met beheerdersrechten, dat is niet iets wat in de code gedaan wordt. Ik heb alleen geen idee wie die rechten heeft.
