### ISSUE TITLE
Datum aanpassen naar commons notatie

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#63]
Dit is meer een uitbreidingsverzoek, dan een storing en heeft wat mij betreft ook geen prioriteit. Maar het zou mooi zijn als op de achtergrond de datums die mensen invoeren omgezet kunnen worden naar de notatie die commons gebruikt (yyyy-mm-dd). Ik denk er niet altijd aan om dit te controleren bij een upload en dan moet een bot het weer aanpassen.

**Comment by JurgenNL** [comment]
Fixed in 267766bbfc2b80b447094b4a7a5f34bee77f8bac
