### ISSUE TITLE
Sjabloon

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#66]
Het oude sjabloon voor Wikiportret voleed niet meer omdat die nog uitging van CC-BY-SA 3.0/GFDL en Wikiportret 2.0 gebruikt CC-BY-SA 4.0. Ik heb daarom een nieuwe sjabloon voor Wikiportet 2.0 uploads aangemaakt: wikiportrait2.
Dit moet alleen nog aangepast worden in regel 26 van formfunctions.php.
Die moet gaan luiden: {{wikiportrait2|VUL_HIER_HET_TICKET_NUMMER_IN}}

**Comment by hay** [comment]
En staat live.
