### ISSUE TITLE
donatieknop 

### ISSUE THREAD

**Issue by Ad-Huikeshoven** [wmnl/wikiportrait#68]
Wikiportret ziet er goed uit op telefoon of tablet. Dat is een fantastische ontwikkeling. 

Een van de dingen die ik mis is een donatiebutton. Zou die er ook in kunnen? Zie http://donations.wikimedia.nl/ en ook de vragen tijdens de ALV van maart 2013 hierover https://nl.wikimedia.org/wiki/Notulen20130323#Vragen_2.

Met vriendelijke groeten,

Ad Huikeshoven

**Comment by hay** [comment]
Is aangepast en gedeployed.

**Comment by Ad-Huikeshoven** [comment]
Hoi Hay,

Enorm bedankt voor dit bericht. Fantastisch dat dit geregeld is!

[image: Inline image 1]

Ik zie in de 'footer' of voettekst een blauwe tekst "Doneer aan Wikimedia".
Als ik daar op klik kom ik op de donatiepagina van de website van Wikimedia
Nederland.
Functioneel doet ie 't - er is een link naar de donatiepagina toegevoegd.
Vergeef me mijn gezeik - bij een donatieknop had ik me iets anders
voorgesteld dan een tekstlink.
Waar ik wel naar benieuwd ben is hoe vaak er op de link geklikt wordt - en
hoe vaak dat een donatie oplevert. Dat hoor ik graag een keer.

Met vriendelijke groeten,

Ad Huikeshoven
