### ISSUE TITLE
Add terms of use and privacy policy

### ISSUE THREAD

**Issue by sjoerddebruin** [wmnl/wikiportrait#69]
A user said he would not upload photos on Wikiportrait, because of the lack of a terms of use and a privacy policy. We should be clear in what will happen when a user uploads a photo.

**Comment by mbch331** [comment]
Zie ook de discussie hier: https://nl.wikipedia.org/w/index.php?title=Help:Helpdesk&oldid=45912026#foto_verschijnt_niet (Vanaf de zin die begint met "terzijde")
Ik heb alleen niet het idee dat de betreffende gebruiker veel zin heeft mee te werken.

**Comment by sjoerddebruin** [comment]
Ik neem contact op met Sandra hierover of Wikimedia Nederland iets kan betekenen.

**Comment by hay** [comment]
Zijn er ergens pagina's waar we naar kunnen linken?

**Comment by sjoerddebruin** [comment]
@hay Het proces is in volle gang. Zodra de teksten er zijn zal ik het laten weten!

**Comment by mbch331** [comment]
De privacyverklaring is er nu, maar er staan een aantal externe links in, die niet gelinkt zijn.
Die moeten nog een link krijgen (met target _blank).

**Comment by sjoerddebruin** [comment]
Done.
