### ISSUE TITLE
Redirect na inloggen

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#77]
Als ik een link uit de mail volg naar een specifieke afbeelding en ik moet opnieuw inloggen, wordt ik na het inloggen niet doorgestuurd naar de originele link, maar altijd naar het overzicht. Dus ik moet eerst inloggen en dan pas de link volgen, of ik moet de link twee keer openen. (Of de juiste afbeelding in de lijst zoeken.)

**Comment by Southparkfan** [comment]
This is related to #65.

**Comment by mbch331** [comment]
https://phabricator.wikimedia.org/T214932
