### ISSUE TITLE
gebruikers krijgen bij uploaden soms een wit scherm

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#85]
Gebruikers die een afbeelding uploaden krijgen bij sommige foto's een wit scherm na het uploaden. De afbeelding is dan niet geüpload (althans staat niet in de lijst en er wordt geen mail getriggerd). Als gebruikers dit melden kan ik het met hetzelfde bestand reproduceren. Zou ik een ander bestand gebruiken met dezelfde informatie uploaden, dan speelt het probleem niet. Upload ik die afbeelding naar Commons, dan werkt dat wel.
Zodra ik weet een voorbeeld foto heb, zal ik die toevoegen.
Ik denk dat stap 1 is het genereren van een foutmelding, waarmee achterhaald kan worden wat de foutmelding is. Daarna kan naar de oplossing van dat probleem gekeken worden.

**Comment by Southparkfan** [comment]
Lijkt op een PHP-error. @hay zou even in de error logs moeten kijken denk ik.

**Comment by mbch331** [comment]
![dorian02](https://cloud.githubusercontent.com/assets/12393536/11818103/cc45fcf4-a358-11e5-933a-56003b1a7fe5.jpg)
Voorbeeld van een foto die niet geüpload kan worden via Wikiportret. Ik heb het zelf zojuist getest en krijg ook een wit scherm.

**Comment by mbch331** [comment]
Lijkt nu uit te komen op een 400 Bad Request, dus issue is nog steeds actueel. Ik heb geen toegang tot de logbestanden om te kunnen zien waar het probleem zit.

**Comment by mbch331** [comment]
https://phabricator.wikimedia.org/T214934
