### ISSUE TITLE
Indicate that wikiportrait is free software and people can contribute

### ISSUE THREAD

**Issue by sjoerddebruin** [wmnl/wikiportrait#86]
More volunteers to help is always a good thing, where could we add a link to our Github project? And are other things, like documentation, needed?

**Comment by JurgenNL** [comment]
What about this icon in the footer?

<img width="1552" alt="screenshot 2016-02-02 11 17 45" src="https://cloud.githubusercontent.com/assets/4716167/12746365/9f48aa28-c99e-11e5-8f72-087b793b4365.png">

**Comment by sjoerddebruin** [comment]
Looks good to me! But be sure to give it a title attribute if you're going for just a icon.
