### ISSUE TITLE
Controle van geldigheid e-mailadres middels bevestigingslink

### ISSUE THREAD

**Issue by mbch331** [wmnl/wikiportrait#91]
Voorstel van Ellywa: Als iemand een foto indient, dan gaat er nog niet direct een mail naar OTRS, maar eerst een mail naar de inzender om te bevestigen dat hij/zij de daadwerkelijk een foto geüpload heeft naar OTRS en dat het opgegeven mailadres ook van hem/haar is.

**Comment by edoderoo** [comment]
Die wens is enkele weken terug ook al door mij op de OTRS-mailinglijst gedaan, en werd toen door iedereen hartelijk omarmd. Vooral ten tijde van het EK voetbal kregen we erg veel onzin-tickets met fake-mail-adressen binnen. Dit zou dat moeten voorkomen.

**Comment by mbch331** [comment]
Begonnen met een voorzichtig opzetje: https://github.com/mbch331/wikiportrait/tree/mailConfirmation
Bijdragen mag (vooral op gebied van teksten is dat zeker welkom).

**Comment by edoderoo** [comment]
Dit is eigenlijk nog steeds wel een issue, en wordt mogelijk steeds groter. Ik kom regelmatig onzinfoto's tegen, maar omdat iedereen een willekeurig reply-to adres in kan geven bij het insturen van een ticket, weet je bij cyberpesten niet eens of de foto wel verstuurd is door degene die als reply-to is ingevuld.

**Comment by mbch331** [comment]
https://phabricator.wikimedia.org/T214938
