### ISSUE TITLE
"archived" gets set when selecting other page for unarchived images

### ISSUE THREAD

**Issue by sjoerddebruin** [wmnl/wikiportrait#93]

**Comment by mbch331** [comment]
Just tested on my phone and don't see the problem.

Non-archived page
http://www.wikiportret.nl/images/overview.php?page=5&archived=0

Archived page
http://www.wikiportret.nl/images/overview.php?page=4&archived=1

**Comment by sjoerddebruin** [comment]
My fault, looks like a bug in the navigation tabs.
