### ISSUE TITLE
Require approval for sharing IP address

### ISSUE THREAD

**Issue by sjoerddebruin** [wmnl/wikiportrait#96]

**Comment by hay** [comment]
Kan hier iets meer context bij?

**Comment by sjoerddebruin** [comment]
Sorry. Kennelijk is het voor onder andere het privacybeleid nodig om expliciete toestemming te vragen voor het opslaan van een IP-adres. Ik vraag mij nu ook eigenlijk af wat voor het nut van het opslaan van deze is.

**Comment by JurgenNL** [comment]
Dit heb ik er destijds ingebouwd om in het geval van eventueel misbruik te kunnen achterhalen waar het vandaan komt en eventueel een blokkade op te leggen. Volgens mij zat dit overigens ook al in de oude versie van Wikiportret, maar dat weet ik niet zeker.
